<?php

use Illuminate\Database\Seeder;

class RelKriteriasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rel_kriterias')->insert([
            [
                'id1'=>'K01-DAT',
                'id2'=>'K01-DAT',
                'nilai'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K01-DAT',
                'id2'=>'K02-BSRHNR',
                'nilai'=>3,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K01-DAT',
                'id2'=>'K03-TNGKTKMPT',
                'nilai'=>5,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K01-DAT',
                'id2'=>'K04-RPTKLN',
                'nilai'=>7,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K01-DAT',
                'id2'=>'K05-KOMPLS',
                'nilai'=>4,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K02-BSRHNR',
                'id2'=>'K01-DAT',
                'nilai'=>1/3,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K02-BSRHNR',
                'id2'=>'K02-BSRHNR',
                'nilai'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K02-BSRHNR',
                'id2'=>'K03-TNGKTKMPT',
                'nilai'=>3,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K02-BSRHNR',
                'id2'=>'K04-RPTKLN',
                'nilai'=>7,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K02-BSRHNR',
                'id2'=>'K05-KOMPLS',
                'nilai'=>4,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K03-TNGKTKMPT',
                'id2'=>'K01-DAT',
                'nilai'=>1/5,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K03-TNGKTKMPT',
                'id2'=>'K02-BSRHNR',
                'nilai'=>1/3,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K03-TNGKTKMPT',
                'id2'=>'K03-TNGKTKMPT',
                'nilai'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K03-TNGKTKMPT',
                'id2'=>'K04-RPTKLN',
                'nilai'=>3,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K03-TNGKTKMPT',
                'id2'=>'K05-KOMPLS',
                'nilai'=>2,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K04-RPTKLN',
                'id2'=>'K01-DAT',
                'nilai'=>1/7,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K04-RPTKLN',
                'id2'=>'K02-BSRHNR',
                'nilai'=>1/7,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K04-RPTKLN',
                'id2'=>'K03-TNGKTKMPT',
                'nilai'=>1/3,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K04-RPTKLN',
                'id2'=>'K04-RPTKLN',
                'nilai'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K04-RPTKLN',
                'id2'=>'K05-KOMPLS',
                'nilai'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K05-KOMPLS',
                'id2'=>'K01-DAT',
                'nilai'=>1/4,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K05-KOMPLS',
                'id2'=>'K02-BSRHNR',
                'nilai'=>1/4,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K05-KOMPLS',
                'id2'=>'K03-TNGKTKMPT',
                'nilai'=>1/2,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K05-KOMPLS',
                'id2'=>'K04-RPTKLN',
                'nilai'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'id1'=>'K05-KOMPLS',
                'id2'=>'K05-KOMPLS',
                'nilai'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
        ]);

    }
}
